spring:
  application:
    name: "mobilelele"
  datasource:
    url: jdbc:mysql://localhost:3306/mobilelele?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  sql:
    init:
      mode: never
  mvc:
    hiddenmethod:
      filter:
        enabled: true

forex:
  api:
    key: ${FOREX_API_KEY}
    url: "https://openexchangerates.org/api/latest.json?app_id={app_id}"
    base: "USD"

offers:
  api:
    baseUrl: "http://localhost:8081"